const { GoogleGenAI } = require('@google/genai');
require('dotenv').config();

// Initialize the Gemini API client
const ai = new GoogleGenAI({
  apiKey: process.env.GEMINI_API_KEY
});

/**
 * Base helper to call the Gemini API and expect structured JSON back.
 * Member 2 (AI Engine) can use this base client for specific prompts.
 * 
 * @param {string} systemPrompt 
 * @param {string} userPrompt 
 * @returns {Promise<Object>} Parsed JSON response
 */
async function generateStructuredAIResponse(systemPrompt, userPrompt) {
  // Mock response for testing and avoiding API rate limits
  console.log('Skipping real Gemini API, returning mock data...');
  return {
    "greeting": "hello",
    "mocked": true,
    "advice": "This is a mock financial advice generated by the system.",
    "analysis": "Mock analysis of your expenses.",
    "score": 85
  };
}

module.exports = {
  ai,
  generateStructuredAIResponse
};
